---

- name: Sample 1 tasks 1
  hosts: localhost
  tags: sample
  tasks:
    - debug: var=inventory_hostname

- name: Sample 1 tasks 2
  hosts: localhost
  tags: another,sample
  tasks:
    - debug: var=inventory_hostname

- name: Show Extra Vars
  hosts: localhost
  tasks:
    - debug: msg="version {{version | default('no_version')}}"
